### ISSUE TITLE
Initial maintenance work

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/docker-image-cleaner#1]
- [x] Add pre-commit
  - [x] Setup pre-commit config
  - [x] Execute pre-commit config
  - [x] Setup pre-commit.ci to run tests, update our pre-commit hook dependencies, and push commits to PRs fixing issues. In practice this means to enable it in the jupyterhub org settings for this repo.
- [x] Add a Docker release GitHub workflow / job
  - [x] Add a quay.io repository under the jupyterhub org
  - [x] Get us a token to use to push to it and set it up as a GitHub Secret, perhaps using a bot account? I've forgot how its done on quay.io.
    - `DOCKER_REGISTRY_USERNAME`, `DOCKER_REGISTRY_PASSWORD` is now available.
  - [x] Make test builds on relevant changes
- [x] Setup dependabot to update github actions in workflows
- [x] Add CHANGELOG.md
- [x] Update README.md
  - [x] Add the typical badges to the README.md file
  - [x] Update the text to be a bit more verbose, helping out a bit more
- [x] Add RELEASE.md
- [x] Add a PyPI release GitHub workflow / job
  - [ ] Release version 1.0.0
  - [ ] Add the `jupyterhub-bot` as a PyPI maintainer to the new project
  - [ ] Setup a GitHub secret `PYPI_PASSWORD` set to a deployment token created on the jupyterhub-bot account maintaining the PyPI project

**Comment by yuvipanda** [comment]
Beautiful!

**Comment by yuvipanda** [comment]
I've created `quay.io/jupyterhub/docker-image-cleaner` - https://quay.io/repository/jupyterhub/docker-image-cleaner

**Comment by yuvipanda** [comment]
I've set DOCKER_REGISTRY_USERNAME and DOCKER_REGISTRY_PASSWORD as secrets here as well

**Comment by consideRatio** [comment]
I cut 1.0.0a0 to setup a PyPI project so I could configure PYPI_PASSWORD etc.
