### ISSUE TITLE
Rename PATH_TO_CHECK?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/docker-image-cleaner#9]
I think PATH_TO_CHECK is too vague. It also deviates by being the only env var influencing this script not prefixed with `IMAGE_GC`.

I think with this package, we should make our configuration more consistent etc, because adopting this package it will be somewhat breaking anyhow so now is the time to do some refactoring.

Related:
- BinderHub deployment image the image cleaner: https://github.com/jupyterhub/binderhub/blob/2cf373bfc4a076d27948860511100fa8710429d2/helm-chart/binderhub/templates/image-cleaner.yaml#L53-L62
- https://github.com/jupyterhub/docker-image-cleaner/blob/2443d911bf0b35903457d4f2bdbf756ce3275c7b/docker_image_cleaner/cleaner.py#L154-L163

**Comment by yuvipanda** [comment]
@consideRatio my preference is to do a 'drop-in' integration of this into binderhub as is before embarking on refactors. This makes it easier to detect breakage caused by issues in the repo split vs issues caused by our refactor. What do you think?

**Comment by consideRatio** [comment]
That sounds reasonable but a bit more work. I suggest we look to make changes pre 1.0.0 though rather than go for a 2.0.0 very soon etc.

**Comment by yuvipanda** [comment]
@consideRatio I think right now you have the energy to do the work, and if so I'll encourage whatever it is you want to do pre 1.0 :)

Renaming sounds good to me. What do you think of using commandline args instead of environment variables?

**Comment by consideRatio** [comment]
Closed by #55

**Comment by consideRatio** [comment]
> What do you think of using commandline args instead of environment variables?

Forgot this note, but it also adds more work to get done. I went for a rename in #55.
